[window]
padding = { x = 15, y = 15 }
dynamic_padding = true
opacity = 0.80
decorations = "Full"
title = "Alacritty Terminal"

[colors]
cursor = { cursor = "#F9A825"}

[font]
normal = { family = "FiraMono Nerd Font", style = "Regular" }
size = 10
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[cursor]
style = { shape = "Beam", blinking = "On"}
blink_interval = 500
thickness = 0.22
blink_timeout = 0

[terminal]
osc52 = "CopyPaste"

